#include "Representative.h"
#include "Senator.h"
#include "Person.h"
#include <string>
#include <iostream>
using namespace std;

const int REPRESENTATIVES = 435;
const int SENATORS = 100;

int main() {
	Representative representatives[REPRESENTATIVES] = { 	Representative(62, "Jerry Carl", "Republican", "2021", "Incumbent", "Alabama 1"), 
								Representative(54, "Barry Morre", "Republican", "2021", "Incumbent", "Alabama 2"),	
								Representative(62, "Mike Rogers", "Republican", "2003", "Incumbent", "Alabama 3"),
								Representative(55, "Robert Aderholt", "Republican", "1997", "Incumbent", "Alabama 4"),
								Representative(66, "Mo Brooks", "Republican", "2011", "Incumbent", "Alabama 5"), 
								Representative(66, "Gary Palmer", "Republican", "2015", "Incumbent", "Alabama 6"),	
								Representative(56, "Terri Sewell", "Democratic", "2011", "Incumbent", "Alabama 7"),
								Representative(87, "Don Young", "Republican", "1973", "Incumbent", "Alaska at-large"),
								Representative(75, "Tom O'Halleran", "Democratic", "2017", "Incumbent", "Arizona 1"),
								Representative(70, "Ann Kirkpatrick", "Democratic", "2019", "Incumbent", "Arizona 2"), 
								Representative(73, "Raul Grijalva", "Democratic", "2003", "Incumbent", "Arizona 3"),
								Representative(62, "Paul Gosar", "Republican", "2011", "Incumbent", "Arizona 4"),
								Representative(62, "Andy Biggs", "Republican", "2017", "Incumbent", "Arizona 5"),
								Representative(59, "David Schweikert", "Republican", "2011", "Incumbent", "Arizona 6"),
								Representative(41, "Ruben Gallego", "Democratic", "2015", "Incumbent", "Arizona 7"),
								Representative(62, "Debbie Lesko", "Republican", "2018", "Incumbent", "Arizona 8"),
								Representative(51, "Greg Stanton", "Democratic", "2019", "Incumbent", "Arizona 9"),
								Representative(55, "Rick Crawford", "Republican", "2011", "Incumbent", "Arkansas 1"),
								Representative(64, "French Hill", "Republican", "2015", "Incumbent", "Arkansas 2"),
								Representative(64, "Steve Womack", "Republican", "2011", "Incumbent", "Arkansas 3"),
								Representative(53, "Bruce Westerman", "Republican", "2015", "Incumbent", "Arkansas 4"),
								Representative(60, "Doug LaMaifa", "Republican", "2013", "Incumbent", "California 1"),
								Representative(57, "Jared Huffman", "Democratic", "2013", "Incumbent", "California 2"),
								Representative(76, "John Garamendi", "Democratic", "2009", "Incumbent", "California 3"),
								Representative(64, "Tom McClintock", "Republican", "2009", "Incumbent", "California 4"),
								Representative(70, "Mike Thompson", "Democratic", "1999", "Incumbent", "California 5"),
								Representative(76, "Doris Matsui", "Democratic", "2005", "Incumbent", "California 6"),
								Representative(56, "Ami Bera", "Democratic", "2013", "Incumbent", "California 7"),
								Representative(50, "Jay Obernolte", "Republican", "2021", "Incumbent", "California 8"),
								Representative(69, "Jerry McNerney", "Democratic", "2007", "Incumbent", "California 9"),
								Representative(34, "Josh Harder", "Democratic", "2019", "Incumbent", "California 10"),
								Representative(68, "Mark DeSaulnier", "Democratic", "2015", "Incumbent", "California 11"),
								Representative(80, "Nancy Pelosi", "Democratic", "1987", "Incumbent", "California 12"),
								Representative(74, "Barbara Lee", "Democratic", "1998", "Incumbent", "California 13"),
								Representative(70, "Jackie Speier", "Democratic", "2008", "Incumbent", "California 14"),
								Representative(40, "Eric Swalwell", "Democratic", "2013", "Incumbent", "California 15"),
								Representative(68, "Jim Costa", "Democratic", "2005", "Incumbent", "California 16"),
								Representative(44, "Ro Khanna", "Democratic", "2017", "Incumbent", "California 17"),
								Representative(78, "Anna Eshoo", "Democratic", "1993", "Incumbent", "California 18"),
								Representative(73, "Zoe Lofgren", "Democratic", "1995", "Incumbent", "California 19"),
								Representative(51, "Jimmy Panetta", "Democratic", "2017", "Incumbent", "California 20"),
								Representative(43, "David Valadao", "Republican", "2021", "Incumbent", "California 21"),
								Representative(47, "Devin Nunes", "Republican", "2003", "Incumbent", "California 22"),
								Representative(56, "Kevin McCarthy", "Republican", "2007", "Incumbent", "California 23"),
								Representative(56, "Salud Carbajal", "Democratic", "2017", "Incumbent", "California 24"),
								Representative(44, "Mike Garcia", "Republican", "2020", "Incumbent", "California 25"),
								Representative(68, "Julia Brownley", "Democratic", "2013", "Incumbent", "California 26"),
								Representative(67, "Judy Chu", "Democratic", "2009", "Incumbent", "California 27"),
								Representative(60, "Adam Schiff", "Democratic", "2001", "Incumbent", "California 28"),
								Representative(57, "Tony Cardenas", "Democratic", "2013", "Incumbent", "California 29"),
								Representative(66, "Brad Sherman", "Democratic", "1997", "Incumbent", "California 30"),
								Representative(41, "Pete Aguilar", "Democratic", "2015", "Incumbent", "California 31"),
								Representative(84, "Grace Napolitano", "Democratic", "1999", "Incumbent", "California 32"),
								Representative(51, "Ted Lieu", "Democratic", "2015", "Incumbent", "California 33"),
								Representative(46, "Jimmy Gomez", "Democratic", "2017", "Incumbent", "California 34"),
								Representative(55, "Norma Torres", "Democratic", "2015", "Incumbent", "California 35"),
								Representative(48, "Raul Ruiz", "Democratic", "2013", "Incumbent", "California 36"),
								Representative(67, "Karen Bass", "Democratic", "2011", "Incumbent", "California 37"),
								Representative(52, "Linda Sanchez", "Democratic", "2003", "Incumbent", "California 38"),
								Representative(58, "Young Kim", "Republican", "2021", "Incumbent", "California 39"),
								Representative(79, "Lucille Roybal-Allard", "Democratic", "1993", "Incumbent", "California 40"),
								Representative(60, "Mark Takano", "Democratic", "2013", "Incumbent", "California 41"),
								Representative(67, "Ken Calvert", "Republican", "1993", "Incumbent", "California 42"),
								Representative(82, "Maxine Waters", "Democratic", "1991", "Incumbent", "California 43"),
								Representative(44, "Nanette Barragan", "Democratic", "2017", "Incumbent", "California 44"),
								Representative(47, "Katie Porter", "Democratic", "2019", "Incumbent", "California 45"),
								Representative(63, "Lou Correa", "Democratic", "2017", "Incumbent", "California 46"),
								Representative(80, "Alan Lowenthal", "Democratic", "2013", "Incumbent", "California 47"),
								Representative(65, "Michelle Steele", "Republican", "2021", "Incumbent", "California 48"),
								Representative(42, "Mike Levin", "Democratic", "2019", "Incumbent", "California 49"),
								Representative(67, "Darrell Issa", "Republican", "2021", "Incumbent", "California 50"),
								Representative(60, "Juan Vargas", "Democratic", "2013", "Incumbent", "California 51"),
								Representative(62, "Scott Peters", "Democratic", "2013", "Incumbent", "California 52"),
								Representative(32, "Sara Jacobs", "Democratic", "2021", "Incumbent", "California 53"), 
								Representative(63, "Diane DeGette", "Democratic", "1997", "Incumbent", "Colorado 1"),
								Representative(36, "Joe Neguse", "Democratic", "2019", "Incumbent", "Colorado 2"),
								Representative(34, "Lauren Boebert", "Republican", "2021", "Incumbent", "Colorado 3"),
								Representative(62, "Ken Buck", "Republican", "2015", "Incumbent", "Colorado 4"),
								Representative(66, "Doug Lamborn", "Republican", "2007", "Incumbent", "Colorado 5"),
								Representative(42, "Jason Crow", "Democratic", "2019", "Incumbent", "Colorado 6"),
								Representative(67, "Ed Perimutter", "Democratic", "2007", "Incumbent", "Colorado 7"), 
								Representative(72, "John B. Larson", "Democratic", "1999", "Incumbent", "Connecticut 1"),
								Representative(67, "Joe Courtney", "Democratic", "2007", "Incumbent", "Connecticut 2"),
								Representative(78, "Rosa DeLauro", "Democratic", "1991", "Incumbent", "Connecticut 3"),
								Representative(54, "Jim Himes", "Democratic", "2009", "Incumbent", "Connecticut 4"),
								Representative(48, "Jahana Hayes", "Democratic", "2019", "Incumbent", "Connecticut 5"),
								Representative(59, "Lisa Blunt Rochester", "Democratic", "2017", "Incumbent", "Delaware at-large"),
								Representative(38, "Matt Gaetz", "Republican", "2017", "Incumbent", "Florida 1"),
								Representative(68, "Neal Dunn", "Republican", "2017", "Incumbent", "Florida 2"),
								Representative(33, "Kat Cammack", "Republican", "2021", "Incumbent", "Florida 3"),
								Representative(68, "John Rutherford", "Republican", "2017", "Incumbent", "Florida 4"),
								Representative(72, "Al Lawson", "Democratic", "2017", "Incumbent", "Florida 5"),
								Representative(47, "Michael Waltz", "Republican", "2019", "Incumbent", "Florida 6"),
								Representative(42, "Stephanie Murphy", "Democratic", "2017", "Incumbent", "Florida 7"),
								Representative(73, "Bill Posey", "Republican", "2009", "Incumbent", "Florida 8"),
								Representative(43, "Darren Soto", "Democratic", "2017", "Incumbent", "Florida 9"),
								Representative(64, "Val Demings", "Democratic", "2017", "Incumbent", "Florida 10"),
								Representative(71, "Daniel Webster", "Republican", "2011", "Incumbent", "Florida 11"),
								Representative(58, "Gus Bilirakis", "Republican", "2007", "Incumbent", "Florida 11"),
								Representative(64, "Charlie Crist", "Democratic", "2017", "Incumbent", "Florida 12"),
								Representative(54, "Kathy Castor", "Democratic", "2007", "Incumbent", "Florida 13"),
								Representative(56, "Scott Franklin", "Republican", "2021", "Incumbent", "Florida 14"),
								Representative(69, "Vern Buchanan", "Republican", "2007", "Incumbent", "Florida 15"),
								Representative(42, "Greg Steube", "Republican", "2019", "Incumbent", "Florida 16"),
								Representative(40, "Brain Mast", "Republican", "2017", "Incumbent", "Florida 17"),
								Representative(42, "Byron Donalds", "Republican", "2021", "Incumbent", "Florida 18"),
								Representative(84, "Alcee Hastings", "Democratic", "1993", "Incumbent", "Florida 19"),
								Representative(72, "Lois Frankel", "Democratic", "2013", "Incumbent", "Florida 20"),
								Representative(54, "Ted Deutch", "Democratic", "2010", "Incumbent", "Florida 21"),
								Representative(54, "Debbie Wasserman Schultz", "Democratic", "2005", "Incumbent", "Florida 22"),
								Representative(78, "Frederica Wilson", "Democratic", "2011", "Incumbent", "Florida 23"),
								Representative(59, "Mario Diaz-Balart", "Republican", "2003", "Incumbent", "Florida 24"),
								Representative(67, "Carlos Gimenez", "Republican", "2021", "Incumbent", "Florida 25"),
								Representative(59, "Maria Elvira Salazar", "Republican", "2021", "Incumbent", "Florida 26"),
								Representative(63, "Buddy Carter", "Republican", "2015", "Incumbent", "Georgia 1"),
								Representative(74, "Sanford Bishop", "Democratic", "1993", "Incumbent", "Georgia 2"),
								Representative(54, "Drew Ferguson", "Republican", "2017", "Incumbent", "Georgia 3"),
								Representative(66, "Hank Johnson", "Democratic", "2007", "Incumbent", "Georgia 4"),
								Representative(42, "Nikema Williams", "Democratic", "2021", "Incumbent", "Georgia 5"),
								Representative(60, "Lucy McBath", "Democratic", "2019", "Incumbent", "Georgia 6"),
								Representative(50, "Carolyn Bourdeaux", "Democratic", "2021", "Incumbent", "Georgia 7"),
								Representative(51, "Austin Scott", "Republican", "2011", "Incumbent", "Georgia 8"),
								Representative(57, "Andrew Clyde", "Republican", "2021", "Incumbent", "Georgia 9"),
								Representative(60, "Jody Hice", "Republican", "2015", "Incumbent", "Georgia 10"),
								Representative(57, "Barry Loudermilk", "Republican", "2015", "Incumbent", "Georgia 11"),
								Representative(69, "Rick W. Allen", "Republican", "2015", "Incumbent", "Georgia 12"),
								Representative(75, "David Scott", "Democratic", "2003", "Incumbent", "Georgia 13"),
								Representative(46, "Marjorie Taylor Greene", "Republican", "2021", "Incumbent", "Georgia 14"),
								Representative(68, "Ed Case", "Democratic", "2019", "Incumbent", "Hawaii 1"),
								Representative(46, "Kai Kahele", "Democratic", "2021", "Incumbent", "Hawaii 2"),
								Representative(59, "Russ Fulcher", "Republican", "2019", "Incumbent", "Idaho 1"),
								Representative(70, "Mike Simpson", "Republican", "1999", "Incumbent", "Idaho 2"),
								Representative(74, "Bobby Rush", "Democratic", "1993", "Incumbent", "Illinois 1"),
								Representative(64, "Robin Kelly", "Democratic", "2013", "Incumbent", "Illinois 2"),
								Representative(56, "Marie Newman", "Democratic", "2021", "Incumbent", "Illinois 3"),
								Representative(64, "Jesus Chuy Garcia", "Democratic", "2019", "Incumbent", "Illinois 4"),
								Representative(62, "Mike Quigley", "Democratic", "2009", "Incumbent", "Illinois 5"),
								Representative(49, "Sean Casten", "Democratic", "2019", "Incumbent", "Illinois 6"),
								Representative(79, "Danny K. Davis", "Democratic", "1997", "Incumbent", "Illinois 7"),
								Representative(47, "Raja Krishnamoorthi", "Democratic", "2017", "Incumbent", "Illinois 8"),
								Representative(76, "Jan Schakowsky", "Democratic", "1999", "Incumbent", "Illinois 9"),
								Representative(59, "Brad Schneider", "Democratic", "2017", "Incumbent", "Illinois 10"),
								Representative(65, "Bill Foster", "Democratic", "2013", "Incumbent", "Illinois 11"),
								Representative(60, "Mike Bost", "Republican", "2015", "Incumbent", "Illinois 12"),
								Representative(51, "Rodney Davis", "Republican", "2013", "Incumbent", "Illinois 13"),
								Representative(34, "Lauren Underwood", "Democratic", "2019", "Incumbent", "Illinois 14"),
								Representative(61, "Mary Miller", "Republican", "2021", "Incumbent", "Illinois 15"),
								Representative(43, "Adam Kinzinger", "Republican", "2011", "Incumbent", "Illinois 16"),
								Representative(59, "Cheri Bustos", "Democratic", "2013", "Incumbent", "Illinois 17"),
								Representative(52, "Darin LaHood", "Republican", "2015", "Incumbent", "Illinois 18"),
								Representative(51, "Frank J. Mrvan", "Democratic", "2021", "Incumbent", "Indiana 1"),
								Representative(57, "Jackie Walorski", "Republican", "2013", "Incumbent", "Indiana 2"),
								Representative(41, "Jim Banks", "Republican", "2017", "Incumbent", "Indiana 3"),
								Representative(75, "Jim Baird", "Republican", "2019", "Incumbent", "Indiana 4"),
								Representative(42, "Victoria Spartz", "Republican", "2021", "Incumbent", "Indiana 5"),
								Representative(64, "Greg Pence", "Republican", "2019", "Incumbent", "Indiana 6"),
								Representative(46, "Andre Carson", "Democratic", "2008", "Incumbent", "Indiana 7"),
								Representative(58, "Larry Bucshon", "Republican", "2011", "Incumbent", "Indiana 8"),
								Representative(37, "Trey Hollingsworth", "Republican", "2017", "Incumbent", "Indiana 9"),
								Representative(37, "Ashley Hinson", "Republican", "2021", "Incumbent", "Iowa 1"),
								Representative(65, "Mariannette Miller-Meeks", "Republican", "2021", "Incumbent", "Iowa 2"),
								Representative(55, "Cindy Axne", "Democratic", "2019", "Incumbent", "Iowa 3"),
								Representative(52, "Randy Feenstra", "Republican", "2021", "Incumbent", "Iowa 4"),
								Representative(44, "Tracey Mann", "Republican", "2021", "Incumbent", "Kansas 1"),
								Representative(33, "Jake LaTurner", "Republican", "2021", "Incumbent", "Kansas 2"),
								Representative(40, "Sharice Davids", "Democratic", "2019", "Incumbent", "Kansas 3"),
								Representative(64, "Ron Estes", "Republican", "2017", "Incumbent", "Kansas 4"),
								Representative(48, "James Comer", "Republican", "2016", "Incumbent", "Kentucky 1"),
								Representative(57, "Brett Guthrie", "Republican", "2009", "Incumbent", "Kentucky 2"),
								Representative(73, "John Yarmuth", "Democratic", "2007", "Incumbent", "Kentucky 3"),
								Representative(50, "Thomas Massie", "Republican", "2012", "Incumbent", "Kentucky 4"),
								Representative(83, "Hal Rogers", "Republican", "1981", "Incumbent", "Kentucky 5"),
								Representative(47, "Andy Barr", "Republican", "2013", "Incumbent", "Kentucky 6"),
								Representative(55, "Steve Scalise", "Republican", "2008", "Incumbent", "Louisiana 1"),
								Representative(0, "Vacant", "Vacant", "Vacant", "Incumbent", "Louisiana 2"),
								Representative(59, "Clay Higgins", "Republican", "2017", "Incumbent", "Louisiana 3"),
								Representative(49, "Mike Johnson", "Republican", "2017", "Incumbent", "Louisiana 4"),
								Representative(0, "Vacant", "Vacant", "Vacant", "Incumbent", "Louisiana 5"),
								Representative(49, "Garret Graves", "Republican", "2015", "Incumbent", "Louisiana 6"),
								Representative(65, "Chellie Pingree", "Democratic", "2009", "Incumbent", "Maine 1"),
								Representative(38, "Jared Golden", "Democratic", "2019", "Incumbent", "Maine 2"),
								Representative(64, "Andy Harris", "Republican", "2011", "Incumbent", "Maryland 1"),
								Representative(75, "Dutch Ruppersberger", "Democratic", "2003", "Incumbent", "Maryland 2"),
								Representative(58, "John Sarbanes", "Democratic", "2007", "Incumbent", "Maryland 3"),
								Representative(59, "Anthony G. Brown", "Democratic", "2017", "Incumbent", "Maryland 4"),
								Representative(81, "Steny Hoyer", "Democratic", "1981", "Incumbent", "Maryland 5"),
								Representative(65, "David Trone", "Democratic", "2019", "Incumbent", "Maryland 6"),
								Representative(72, "Kweisi Mfume", "Democratic", "2020", "Incumbent", "Maryland 7"),
								Representative(58, "Jamie Raskin", "Democratic", "2017", "Incumbent", "Maryland 8"),
								Representative(72, "Richard Neal", "Democratic", "1989", "Incumbent", "Massachusetts 1"),
								Representative(61, "Jim McGovern", "Democratic", "1997", "Incumbent", "Massachusetts 2"),
								Representative(47, "Lori Trahan", "Democratic", "2019", "Incumbent", "Massachusetts 3"),
								Representative(33, "Jake Auchincloss", "Democratic", "2021", "Incumbent", "Massachusetts 4"),
								Representative(57, "Katherine Clark", "Democratic", "2013", "Incumbent", "Massachusetts 5"),
								Representative(42, "Seth Moulton", "Democratic", "2015", "Incumbent", "Massachusetts 6"),
								Representative(47, "Ayanna Pressley", "Democratic", "2019", "Incumbent", "Massachusetts 7"),
								Representative(65, "Stephen F. Lynch", "Democratic", "2001", "Incumbent", "Massachusetts 8"),
								Representative(68, "Bill Keating", "Democratic", "2011", "Incumbent", "Massachusetts 9"),
								Representative(74, "Jack Bergman", "Republican", "2017", "Incumbent", "Michigan 1"),
								Representative(52, "Bill Huizenga", "Republican", "2011", "Incumbent", "Michigan 2"),
								Representative(33, "Peter Meijer", "Republican", "2021", "Incumbent", "Michigan 3"),
								Representative(59, "John Moolenaar", "Republican", "2015", "Incumbent", "Michigan 4"),
								Representative(62, "Dan Kildee", "Democratic", "2013", "Incumbent", "Michigan 5"),
								Representative(67, "Fred Upton", "Republican", "1987", "Incumbent", "Michigan 6"),
								Representative(69, "Tim Walberg", "Republican", "2011", "Incumbent", "Michigan 7"),
								Representative(44, "Elissa Slotkin", "Democratic", "2019", "Incumbent", "Michigan 8"),
								Representative(60, "Andy Levin", "Democratic", "2019", "Incumbent", "Michigan 9"),
								Representative(54, "Lisa McClain", "Republican", "2021", "Incumbent", "Michigan 10"),
								Representative(37, "Haley Stevens", "Democratic", "2019", "Incumbent", "Michigan 11"),
								Representative(67, "Debbie Dingell", "Democratic", "2015", "Incumbent", "Michigan 12"),
								Representative(44, "Rashida Tlaib", "Democratic", "2019", "Incumbent", "Michigan 13"),
								Representative(66, "Brenda Lawrence", "Democratic", "2015", "Incumbent", "Michigan 14"),
								Representative(58, "Jim Hagedorn", "Republican", "2019", "Incumbent", "Minnesota 1"),
								Representative(49, "Angie Craig", "Democratic", "2019", "Incumbent", "Minnesota 2"),
								Representative(52, "Dean Phillips", "Democratic", "2019", "Incumbent", "Minnesota 3"),
								Representative(66, "Betty McCollum", "Democratic", "2001", "Incumbent", "Minnesota 4"),
								Representative(38, "Ilhan Omar", "Democratic", "2019", "Incumbent", "Minnesota 5"),
								Representative(60, "Tom Emmer", "Republican", "2015", "Incumbent", "Minnesota 6"),
								Representative(55, "Michelle Fischbach", "Republican", "2021", "Incumbent", "Minnesota 7"),
								Representative(54, "Pete Stauber", "Republican", "2019", "Incumbent", "Minnesota 8"),
								Representative(55, "Trent Kelly", "Republican", "2015", "Incumbent", "Mississippi 1"),
								Representative(73, "Bennie Thompson", "Democratic", "1993", "Incumbent", "Mississippi 2"),
								Representative(51, "Michael Guest", "Republican", "2019", "Incumbent", "Mississippi 3"),
								Representative(51, "Steven Palazzo", "Republican", "2011", "Incumbent", "Mississippi 4"),
								Representative(44, "Cori Bush", "Democratic", "2021", "Incumbent", "Missouri 1"),
								Representative(58, "Ann Wagner", "Republican", "2013", "Incumbent", "Missouri 2"),
								Representative(68, "Blaine Luetkemeyer", "Republican", "2009", "Incumbent", "Missouri 3"),
								Representative(60, "Vicky Hartzler", "Republican", "2011", "Incumbent", "Missouri 4"),
								Representative(76, "Emanuel Cleaver", "Democratic", "2005", "Incumbent", "Missouri 5"),
								Representative(57, "Sam Graves", "Republican", "2001", "Incumbent", "Missouri 6"),
								Representative(65, "Billy Long", "Republican", "2011", "Incumbent", "Missouri 7"),
								Representative(40, "Jason Smith", "Republican", "2013", "Incumbent", "Missouri 8"),
								Representative(60, "Matt Rosendale", "Republican", "2021", "Incumbent", "Montana at-large"),
								Representative(60, "Jeff Fortenberry", "Republican", "2005", "Incumbent", "Nebraska 1"),
								Representative(57, "Don Bacon", "Republican", "2017", "Incumbent", "Nebraska 2"),
								Representative(50, "Adrian Smith", "Republican", "2007", "Incumbent", "Nebraska 3"),
								Representative(70, "Dina Titus", "Democratic", "2013", "Incumbent", "Nevada 1"),
								Representative(62, "Mark Amodei", "Republican", "2011", "Incumbent", "Nevada 2"),
								Representative(54, "Susie Lee", "Democratic", "2019", "Incumbent", "Nevada 3"),
								Representative(47, "Steven Horsford", "Democratic", "2019", "Incumbent", "Nevada 4"),
								Representative(40, "Chris Pappas", "Democratic", "2019", "Incumbent", "New Hampshire 1"),
								Representative(64, "Ann McLane Kuster", "Democratic", "2013", "Incumbent", "New Hampshire 2"),
								Representative(62, "Donald Norcross", "Democratic", "2014", "Incumbent", "New Jersey 1"),
								Representative(68, "Jeff Van Drew", "Republican", "2019", "Incumbent", "New Jersey 2"),
								Representative(38, "Andy Kim", "Democratic", "2019", "Incumbent", "New Jersey 3"),
								Representative(68, "Chris Smith", "Republican", "1981", "Incumbent", "New Jersey 4"),
								Representative(46, "Josh Gottheimer", "Democratic", "2017", "Incumbent", "New Jersey 5"),
								Representative(69, "Frank Pallone", "Democratic", "1988", "Incumbent", "New Jersey 6"),
								Representative(55, "Tom Malinowski", "Democratic", "2019", "Incumbent", "New Jersey 7"),
								Representative(70, "Albio Sires", "Democratic", "2006", "Incumbent", "New Jersey 8"),
								Representative(84, "Bill Pascrell", "Democratic", "1997", "Incumbent", "New Jersey 9"),
								Representative(62, "Donald Payne Jr.", "Democratic", "2012", "Incumbent", "New Jersey 10"),
								Representative(49, "Mikie Sherrill", "Democratic", "2019", "Incumbent", "New Jersey 11"),
								Representative(76, "Bonnie Watson Coleman", "Democratic", "2015", "Incumbent", "New Jersey 12"),
								Representative(0, "Vacant", "Vacant", "Vacant", "Incumbent", "New Mexico 1"),	
								Representative(57, "Yvette Herrell", "Republican", "2021", "Incumbent", "New Mexico 2"),
								Representative(61, "Teresa Leger Fernandez", "Democratic", "2021", "Incumbent", "New Mexico 3"),
								Representative(41, "Lee Zeldin", "Republican", "2015", "Incumbent", "New York 1"),
								Representative(36, "Andrew Garbarino", "Republican", "2021", "Incumbent", "New York 2"),
								Representative(58, "Thomas Suozzi", "Democratic", "2017", "Incumbent", "New York 3"),
								Representative(56, "Kathleen Rice", "Democratic", "2015", "Incumbent", "New York 4"),
								Representative(67, "Gregory Meeks", "Democratic", "1998", "Incumbent", "New York 5"),
								Representative(45, "Grace Meng", "Democratic", "2013", "Incumbent", "New York 6"),
								Representative(67, "Nydia Velazquez", "Democratic", "1993", "Incumbent", "New York 7"),
								Representative(50, "Hakeem Jeffries", "Democratic", "2013", "Incumbent", "New York 8"),
								Representative(56, "Yvette Clarke", "Democratic", "2007", "Incumbent", "New York 9"),
								Representative(73, "Jerry Nadler", "Democratic", "1992", "Incumbent", "New York 10"),
								Representative(40, "Nicole Malliotakis", "Republican", "2021", "Incumbent", "New York 11"),
								Representative(75, "Carolyn Maloney", "Democratic", "1993", "Incumbent", "New York 12"),
								Representative(66, "Adriano Espaillat", "Democratic", "2017", "Incumbent", "New York 13"),
								Representative(31, "Alexandria Ocasio-Cortez", "Democratic", "2019", "Incumbent", "New York 14"),
								Representative(33, "Ritchie Torres", "Democratic", "2021", "Incumbent", "New York 15"),
								Representative(44, "Jamaal Bowman", "Democratic", "2021", "Incumbent", "New York 16"),
								Representative(33, "Mondaire Jones", "Democratic", "2021", "Incumbent", "New York 17"),
								Representative(54, "Sean Patrick Maloney", "Democratic", "2013", "Incumbent", "New York 18"),
								Representative(44, "Antonio Delgado", "Democratic", "2019", "Incumbent", "New York 19"),
								Representative(71, "Paul Tonko", "Democratic", "2009", "Incumbent", "New York 20"),
								Representative(36, "Elise Stefanik", "Republican", "2015", "Incumbent", "New York 21"),
								Representative(60, "Claudia Tenney", "Republican", "2021", "Incumbent", "New York 22"),
								Representative(49, "Tom Reed", "Republican", "2010", "Incumbent", "New York 23"),
								Representative(58, "John Katko", "Republican", "2015", "Incumbent", "New York 24"),
								Representative(63, "Joseph Morelle", "Democratic", "2018", "Incumbent", "New York 25"),
								Representative(61, "Brian Higgins", "Democratic", "2005", "Incumbent", "New York 26"),
								Representative(54, "Chris Jacobs", "Republican", "2020", "Incumbent", "New York 27"),
								Representative(73, "G. K. Butterfield", "Democratic", "2004", "Incumbent", "North Carolina 1"),
								Representative(57, "Deborah Ross", "Democratic", "2021", "Incumbent", "North Carolina 2"),
								Representative(58, "Greg Murphy", "Republican", "2019", "Incumbent", "North Carolina 3"),
								Representative(80, "David Price", "Democratic", "1997", "Incumbent", "North Carolina 4"),
								Representative(77, "Virginia Foxx", "Republican", "2005", "Incumbent", "North Carolina 5"),
								Representative(64, "Kathy Manning", "Democratic", "2021", "Incumbent", "North Carolina 6"),
								Representative(49, "David Rouzer", "Republican", "2015", "Incumbent", "North Carolina 7"),
								Representative(49, "Richard Hudson", "Republican", "2013", "Incumbent", "North Carolina 8"),
								Representative(56, "Dan Bishop", "Republican", "2019", "Incumbent", "North Carolina 9"),
								Representative(45, "Patrick McHenry", "Republican", "2005", "Incumbent", "North Carolina 10"),
								Representative(25, "Madison Cawthorn", "Republican", "2021", "Incumbent", "North Carolina 11"),
								Representative(74, "Alma Adams", "Democratic", "2014", "Incumbent", "North Carolina 12"),
								Representative(49, "Ted Budd", "Republican", "2017", "Incumbent", "North Carolina 13"),
								Representative(44, "Kelly Armstrong", "Republican", "2019", "Incumbent", "North Dakota at-large"),
								Representative(68, "Steve Chabot", "Republican", "2011", "Incumbent", "Ohio 1"),
								Representative(62, "Brad Wenstrup", "Republican", "2013", "Incumbent", "Ohio 2"),
								Representative(71, "Joyce Beatty", "Democratic", "2013", "Incumbent", "Ohio 3"),
								Representative(57, "Jim Jordan", "Republican", "2007", "Incumbent", "Ohio 4"),
								Representative(64, "Bob Latta", "Republican", "2007", "Incumbent", "Ohio 5"),
								Representative(66, "Bill Johnson", "Republican", "2011", "Incumbent", "Ohio 6"),
								Representative(66, "Bob Gibbs", "Republican", "2011", "Incumbent", "Ohio 7"),
								Representative(51, "Warren Davidson", "Republican", "2016", "Incumbent", "Ohio 8"),
								Representative(74, "Marcy Kaptur", "Democratic", "1983", "Incumbent", "Ohio 9"),
								Representative(61, "Mike Turner", "Republican", "2003", "Incumbent", "Ohio 10"),
								Representative(0, "Vacant", "Vacant", "Vacant", "Incumbent", "Ohio 11"),
								Representative(59, "Troy Balderson", "Republican", "2018", "Incumbent", "Ohio 12"),
								Representative(47, "Tim Ryan", "Democratic", "2003", "Incumbent", "Ohio 13"),
								Representative(64, "David Joyce", "Republican", "2013", "Incumbent", "Ohio 14"),
								Representative(55, "Steve Stivers", "Republican", "2011", "Incumbent", "Ohio 15"),
								Representative(36, "Anthony Gonzalez", "Republican", "2019", "Incumbent", "Ohio 16"),
								Representative(59, "Kevin Hern", "Republican", "2018", "Incumbent", "Oklahoma 1"),
								Representative(43, "Markwayne Mullin", "Republican", "2013", "Incumbent", "Oklahoma 2"),
								Representative(61, "Frank Lucas", "Republican", "1994", "Incumbent", "Oklahoma 3"),
								Representative(71, "Tom Cole", "Republican", "2003", "Incumbent", "Oklahoma 4"),
								Representative(47, "Stephanie Bice", "Republican", "2021", "Incumbent", "Oklahoma 5"),
								Representative(66, "Suzanne Bonamici", "Democratic", "2012", "Incumbent", "Oregon 1"),
								Representative(69, "Cliff Bentz", "Republican", "2021", "Incumbent", "Oregon 2"),
								Representative(72, "Earl Blumenauer", "Democratic", "1996", "Incumbent", "Oregon 3"),
								Representative(73, "Peter DeFazio", "Democratic", "1987", "Incumbent", "Oregon 4"),
								Representative(69, "Kurt Schrader", "Democratic", "2009", "Incumbent", "Oregon 5"),
								Representative(47, "Brian Fitzpatrick", "Republican", "2017", "Incumbent", "Pennsylvania 1"),
								Representative(44, "Brendan Boyle", "Democratic", "2015", "Incumbent", "Pennsylvania 2"),
								Representative(66, "Dwight Evans", "Democratic", "2016", "Incumbent", "Pennsylvania 3"),
								Representative(61, "Madeleine Dean", "Democratic", "2019", "Incumbent", "Pennsylvania 4"),
								Representative(61, "Mary Gay Scanlon", "Democratic", "2018", "Incumbent", "Pennsylvania 5"),
								Representative(53, "Chrissy Houlahan", "Democratic", "2019", "Incumbent", "Pennsylvania 6"),
								Representative(63, "Susan Wild", "Democratic", "2018", "Incumbent", "Pennsylvania 7"),
								Representative(59, "Matt Cartwright", "Democratic", "2013", "Incumbent", "Pennsylvania 8"),
								Representative(57, "Dan Meuser", "Republican", "2019", "Incumbent", "Pennsylvania 9"),
								Representative(58, "Scott Perry", "Republican", "2013", "Incumbent", "Pennsylvania 10"),
								Representative(57, "Lloyd Smucker", "Republican", "2017", "Incumbent", "Pennsylvania 11"),
								Representative(55, "Fred Keller", "Republican", "2019", "Incumbent", "Pennsylvania 12"),
								Representative(64, "John Joyce", "Republican", "2019", "Incumbent", "Pennsylvania 13"),
								Representative(37, "Guy Reschenthaler", "Republican", "2019", "Incumbent", "Pennsylvania 14"),
								Representative(61, "Glenn Thompson", "Republican", "2009", "Incumbent", "Pennsylvania 15"),
								Representative(72, "Mike Kelly", "Republican", "2011", "Incumbent", "Pennsylvania 16"),
								Representative(36, "Conor Lamb", "Democratic", "2018", "Incumbent", "Pennsylvania 17"),
								Representative(67, "Mike Doyle", "Democratic", "1995", "Incumbent", "Pennsylvania 18"),
								Representative(59, "David Cicilline", "Democratic", "2011", "Incumbent", "Rhode Island 1"),
								Representative(56, "James Langevin", "Democratic", "2001", "Incumbent", "Rhode Island 2"),
								Representative(43, "Nancy Mace", "Republican", "2021", "Incumbent", "South Carolina 1"),
								Representative(73, "Joe Wilson", "Republican", "2001", "Incumbent", "South Carolina 2"),
								Representative(55, "Jeff Duncan", "Republican", "2011", "Incumbent", "South Carolina 3"),
								Representative(36, "William Timmons", "Republican", "2019", "Incumbent", "South Carolina 4"),
								Representative(67, "Ralph Norman", "Republican", "2017", "Incumbent", "South Carolina 5"),
								Representative(80, "Jim Clyburn", "Democratic", "1993", "Incumbent", "South Carolina 6"),
								Representative(63, "Tom Rice", "Republican", "2013", "Incumbent", "South Carolina 7"),
								Representative(44, "Dusty Johnson", "Republican", "2019", "Incumbent", "South Dakota at-large"),
								Representative(61, "Diana Harshbarger", "Republican", "2021", "Incumbent", "Tennessee 1"),
								Representative(56, "Tim Burchett", "Republican", "2019", "Incumbent", "Tennessee 2"),
								Representative(58, "Chuck Fleischmann", "Republican", "2011", "Incumbent", "Tennessee 3"),
								Representative(57, "Scott DesJarlais", "Republican", "2011", "Incumbent", "Tennessee 4"),
								Representative(66, "Jim Cooper", "Democratic", "2003", "Incumbent", "Tennessee 5"),
								Representative(56, "John Rose", "Republican", "2019", "Incumbent", "Tennessee 6"),
								Representative(56, "Mark E. Green", "Republican", "2019", "Incumbent", "Tennessee 7"),
								Representative(54, "David Kustoff", "Republican", "2017", "Incumbent", "Tennessee 8"),	
								Representative(71, "Steve Cohen", "Democratic", "2007", "Incumbent", "Tennessee 9"),
								Representative(67, "Louie Gohmert", "Republican", "2005", "Incumbent", "Texas 1"),	
								Representative(37, "Dan Crenshaw", "Republican", "2019", "Incumbent", "Texas 2"),
								Representative(48, "Van Taylor", "Republican", "2019", "Incumbent", "Texas 3"),	
								Representative(53, "Pat Fallon", "Republican", "2021", "Incumbent", "Texas 4"),
								Representative(38, "Lance Gooden", "Republican", "2019", "Incumbent", "Texas 5"),	
								Representative(0, "Vacant", "Vacant", "Vacant", "Incumbent", "Texas 6"),
								Representative(46, "Lizzie Pannill Fletcher", "Democratic", "2019", "Incumbent", "Texas 7"),	
								Representative(65, "Kevin Brady", "Republican", "1997", "Incumbent", "Texas 8"),
								Representative(73, "Al Green", "Democratic", "2005", "Incumbent", "Texas 9"),	
								Representative(59, "Michael McCaul", "Republican", "2005", "Incumbent", "Texas 10"),
								Representative(42, "August Pfluger", "Republican", "2021", "Incumbent", "Texas 11"),	
								Representative(78, "Kay Granger", "Republican", "1997", "Incumbent", "Texas 12"),
								Representative(53, "Ronny Jackson", "Republican", "2021", "Incumbent", "Texas 13"),	
								Representative(67, "Randy Weber", "Republican", "2013", "Incumbent", "Texas 14"),
								Representative(53, "Vicente Gonzalez", "Democratic", "2017", "Incumbent", "Texas 15"),	
								Representative(51, "Veronica Escobar", "Democratic", "2019", "Incumbent", "Texas 16"),
								Representative(66, "Pete Sessions", "Republican", "2021", "Incumbent", "Texas 17"),	
								Representative(71, "Sheila Jackson Lee", "Democratic", "1995", "Incumbent", "Texas 18"),
								Representative(49, "Jodey Arrington", "Republican", "2017", "Incumbent", "Texas 19"),	
								Representative(46, "Joaquin Castro", "Democratic", "2013", "Incumbent", "Texas 20"),
								Representative(48, "Chip Roy", "Republican", "2019", "Incumbent", "Texas 21"),	
								Representative(52, "Troy Nehls", "Republican", "2021", "Incumbent", "Texas 22"),
								Representative(40, "Tony Gonzales", "Republican", "2021", "Incumbent", "Texas 23"),	
								Representative(50, "Beth Van Duyne", "Republican", "2021", "Incumbent", "Texas 24"),
								Representative(71, "Roger Williams", "Republican", "2013", "Incumbent", "Texas 25"),	
								Representative(70, "Michael C. Burgess", "Republican", "2003", "Incumbent", "Texas 26"),
								Representative(45, "Michael Cloud", "Republican", "2018", "Incumbent", "Texas 27"),	
								Representative(65, "Henry Cuellar", "Democratic", "2005", "Incumbent", "Texas 28"),
								Representative(70, "Sylvia Garcia", "Democratic", "2019", "Incumbent", "Texas 29"),	
								Representative(85, "Eddie Bernice Johnson", "Democratic", "1993", "Incumbent", "Texas 30"),
								Representative(79, "John Carter", "Republican", "2003", "Incumbent", "Texas 31"),	
								Representative(37, "Colin Allred", "Democratic", "2019", "Incumbent", "Texas 32"),
								Representative(50, "Marc Veasey", "Democratic", "2013", "Incumbent", "Texas 33"),	
								Representative(58, "Filemon Vela Jr.", "Democratic", "2013", "Incumbent", "Texas 34"),
								Representative(74, "Lloyd Doggett", "Democratic", "1995", "Incumbent", "Texas 35"),	
								Representative(72, "Brian Babin", "Republican", "2015", "Incumbent", "Texas 36"),
								Representative(40, "Blake Moore", "Republican", "2021", "Incumbent", "Utah 1"),
								Representative(60, "Chris Stewart", "Republican", "2013", "Incumbent", "Utah 2"),
								Representative(60, "John Curtis", "Republican", "2017", "Incumbent", "Utah 3"),
								Representative(69, "Burgess Owens", "Republican", "2021", "Incumbent", "Utah 4"),
								Representative(73, "Peter Welch", "Democratic", "2007", "Incumbent", "Vermont at-large"),
								Representative(62, "Rob Wittman", "Republican", "2007", "Incumbent", "Virginia 1"),
								Representative(45, "Elaine Luria", "Democratic", "2019", "Incumbent", "Virginia 2"),
								Representative(73, "Bobby Scott", "Democratic", "1993", "Incumbent", "Virginia 3"),
								Representative(59, "Donald McEachin", "Democratic", "2017", "Incumbent", "Virginia 4"),
								Representative(55, "Bob Good", "Republican", "2021", "Incumbent", "Virginia 5"),
								Representative(49, "Ben Cline", "Republican", "2019", "Incumbent", "Virginia 6"),
								Representative(41, "Abigail Spanberger", "Democratic", "2019", "Incumbent", "Virginia 7"),
								Representative(70, "Don Beyer", "Democratic", "2015", "Incumbent", "Virginia 8"),	
								Representative(63, "Morgan Griffith", "Republican", "2011", "Incumbent", "Virginia 9"),
								Representative(52, "Jennifer Wexton", "Democratic", "2019", "Incumbent", "Virginia 10"),
								Representative(70, "Gerry Connolly", "Democratic", "2009", "Incumbent", "Virginia 11"),
								Representative(59, "Suzan DelBene", "Democratic", "2012", "Incumbent", "Washington 1"),
								Representative(55, "Rick Larsen", "Democratic", "2001", "Incumbent", "Washington 2"),
								Representative(42, "Jaime Herrera Beutler", "Republican", "2011", "Incumbent", "Washington 3"),
								Representative(65, "Dan Newhouse", "Republican", "2015", "Incumbent", "Washington 4"),
								Representative(51, "Cathy McMorris Rodgers", "Republican", "2005", "Incumbent", "Washington 5"),
								Representative(47, "Derek Kilmer", "Democratic", "2013", "Incumbent", "Washington 6"),
								Representative(55, "Pramila Jayapal", "Democratic", "2017", "Incumbent", "Washington 7"),
								Representative(52, "Kim Schrier", "Democratic", "2019", "Incumbent", "Washington 8"),
								Representative(55, "Adam Smith", "Democratic", "1997", "Incumbent", "Washington 9"),
								Representative(58, "Marilyn Strickland", "Democratic", "2021", "Incumbent", "Washington 10"),
								Representative(73, "David McKinley", "Republican", "2011", "Incumbent", "West Virginia 1"),
								Representative(49, "Alex Mooney", "Republican", "2015", "Incumbent", "West Virginia 2"),
								Representative(70, "Carol Miller", "Republican", "2019", "Incumbent", "West Virginia 3"),
								Representative(40, "Bryan Steil", "Republican", "2019", "Incumbent", "Wisconsin 1"),
								Representative(56, "Mark Pocan", "Democratic", "2013", "Incumbent", "Wisconsin 2"),
								Representative(58, "Ron Kind", "Democratic", "1997", "Incumbent", "Wisconsin 3"),
								Representative(69, "Gwen Moore", "Democratic", "2005", "Incumbent", "Wisconsin 4"),
								Representative(57, "Scott Fitzgerald", "Republican", "2021", "Incumbent", "Wisconsin 5"),
								Representative(65, "Glenn Grothman", "Republican", "2015", "Incumbent", "Wisconsin 6"),
								Representative(63, "Tom Tiffany", "Republican", "2020", "Incumbent", "Wisconsin 7"),
								Representative(37, "Mike Gallagher", "Republican", "2017", "Incumbent", "Wisconsin 8"),
								Representative(54, "Liz Cheney", "Republican", "2017", "Incumbent", "Wyoming at-large")	};
	Senator senators[SENATORS] = { 	Senator(86, "Richard Shelby", "Republican", "1987", "Incumbent", "Alabama"), 
					Senator(66, "Tommy Tuberville", "Republican", "2021", "Incumbent", "Alabama"),
					Senator(63, "Lisa Murkowski", "Republican", "2002", "Incumbent", "Alaska"), 
					Senator(56, "Dan Sullivan", "Republican", "2015", "Incumbent", "Alaska"), 
					Senator(44, "Kyrsten Sinema", "Democratic", "2019", "Incumbent", "Arizona"),
					Senator(57, "Mark Kelly", "Democratic", "2020", "Incumbent", "Arizona"),
					Senator(70, "John Boozman", "Republican", "2011", "Incumbent", "Arkansas"), 
					Senator(43, "Tom Cotton", "Republican", "2015", "Incumbent", "Arkansas"),
					Senator(87, "Dianne Feinstein", "Democratic", "1992", "Incumbent", "California"),
					Senator(48, "Alex Padilla", "Democratic", "2021", "Incumbent", "California"),
					Senator(56, "Michael Bennet", "Democratic", "2009", "Incumbent", "Colorado"),
					Senator(69, "John Hickenlooper", "Democratic", "2021", "Incumbent", "Colorado"),
					Senator(75, "Richard Blumenthal", "Democratic", "2011", "Incumbent", "Connecticut"),
					Senator(47, "Chris Murphy", "Democratic", "2013", "Incumbent", "Connecticut"),
					Senator(74, "Tom Carper", "Democratic", "2001", "Incumbent", "Delaware"),
					Senator(57, "Chris Coons", "Democratic", "2010", "Incumbent", "Delaware"),
					Senator(49, "Marco Rubio", "Republican", "2011", "Incumbent", "Florida"),
					Senator(68, "Rick Scott", "Republican", "2019", "Incumbent", "Florida"),
					Senator(34, "Jon Ossoff", "Democratic", "2021", "Incumbent", "Georgia"),
					Senator(51, "Raphael Warnock", "Democratic", "2021", "Incumbent", "Gerogia"),
					Senator(48, "Brian Schatz", "Democratic", "2012", "Incumbent", "Hawaii"),
					Senator(73, "Mazie Hirono", "Democratic", "2013", "Incumbent", "Hawaii"),
					Senator(69, "Mike Crapo", "Republican", "1999", "Incumbent", "Idaho"),
					Senator(77, "Jim Risch", "Republican", "2009", "Incumbent", "Idaho"),
					Senator(76, "Dick Durbin", "Democratic", "1997", "Incumbent", "Illinois"),
					Senator(53, "Tammy Duckworth", "Democratic", "2017", "Incumbent", "Illinois"),
					Senator(48, "Todd Young", "Republican", "2017", "Incumbent", "Indiana"),
					Senator(66, "Mike Braun", "Republican", "2019", "Incumbent", "Indiana"),
					Senator(87, "Chuck Grassley", "Republican", "1981", "Incumbent", "Iowa"),
					Senator(50, "Joni Ernst", "Republican", "2015", "Incumbent", "Iowa"),
					Senator(66, "Jerry Moran", "Republican", "2011", "Incumbent", "Kansas"),
					Senator(60, "Roger Marshall", "Republican", "2021", "Incumbent", "Kansas"),
					Senator(79, "Mitch McConnell", "Republican", "1985", "Incumbent", "Kentucky"),
					Senator(58, "Rand Paul", "Republican", "2011", "Incumbent", "Kentucky"),
					Senator(63, "Bill Cassidy", "Republican", "2015", "Incumbent", "Louisiana"),
					Senator(69, "John Kennedy", "Republican", "2017", "Incumbent", "Louisiana"),
					Senator(68, "Susan Collins", "Republican", "1997", "Incumbent", "Maine"),
					Senator(76, "Angus King", "Independent", "2013", "Incumbent", "Maine"),
					Senator(77, "Ben Cardin", "Democratic", "2007", "Incumbent", "Maryland"),
					Senator(62, "Chris Van Hollen", "Democratic", "2017", "Incumbent", "Maryland"),
					Senator(71, "Elizabeth Warren", "Democratic", "2013", "Incumbent", "Massachusetts"),
					Senator(74, "Ed Markey", "Democratic", "2013", "Incumbent", "Massachusetts"),
					Senator(70, "Debbie Stabenow", "Democratic", "2001", "Incumbent", "Michigan"),
					Senator(62, "Gary Peters", "Democratic", "2015", "Incumbent", "Michigan"),
					Senator(60, "Amy Klobuchar", "Democratic", "2007", "Incumbent", "Minessota"),
					Senator(63, "Tina Smith", "Democratic", "2018", "Incumbent", "Minessota"),
					Senator(69, "Roger Wicker", "Republican", "2007", "Incumbent", "Mississippi"),
					Senator(61, "Cindy Hyde-Smith", "Republican", "2018", "Incumbent", "Mississippi"),
					Senator(71, "Roy Blunt", "Republican", "2011", "Incumbent", "Missouri"),
					Senator(41, "Josh Hawley", "Republican", "2019", "Incumbent", "Missouri"),
					Senator(64, "Jon Tester", "Democratic", "2007", "Incumbent", "Montana"),
					Senator(58, "Steve Daines", "Republican", "2015", "Incumbent", "Montana"),
					Senator(70, "Deb Fischer", "Republican", "2013", "Incumbent", "Nebraska"),
					Senator(49, "Ben Sasse", "Republican", "2015", "Incumbent", "Nebraska"),
					Senator(56, "Catherine Cortez Masto", "Democratic", "2017", "Incumbent", "Nevada"),
					Senator(63, "Jacky Rosen", "Democratic", "2019", "Incumbent", "Nevada"),
					Senator(74, "Jeanne Shaheen", "Democratic", "2009", "Incumbent", "New Hampshire"),
					Senator(63, "Maggie Hassan", "Democratic", "2017", "Incumbent", "New Hampshire"),
					Senator(67, "Bob Menendez", "Democratic", "2006", "Incumbent", "New Jersey"),
					Senator(51, "Cory Booker", "Democratic", "2013", "Incumbent", "New Jersey"),
					Senator(49, "Martin Heinrich", "Democratic", "2013", "Incumbent", "New Mexico"),
					Senator(48, "Ben Ray Lujan", "Democratic", "2021", "Incumbent", "New Mexico"),
					Senator(70, "Chuck Schumer", "Democratic", "1999", "Incumbent", "New York"),
					Senator(54, "Kirsten Gillibrand", "Democratic", "2009", "Incumbent", "New York"),
					Senator(65, "Richard Burr", "Republican", "2005", "Incumbent", "North Carolina"),
					Senator(60, "Thom Tillis", "Republican", "2015", "Incumbent", "North Carolina"),
					Senator(64, "John Hoeven", "Republican", "2011", "Incumbent", "North Dakota"),
					Senator(60, "Kevin Cramer", "Republican", "2019", "Incumbent", "North Dakota"),
					Senator(68, "Sherrod Brown", "Democratic", "2007", "Incumbent", "Ohio"),
					Senator(65, "Rob Portman", "Republican", "2011", "Incumbent", "Ohio"),
					Senator(86, "Jim Inhofe", "Republican", "1994", "Incumbent", "Oklahoma"),
					Senator(53, "James Lankford", "Republican", "2015", "Incumbent", "Oklahoma"),
					Senator(71, "Ron Wyden", "Democratic", "1996", "Incumbent", "Oregon"),
					Senator(64, "Jeff Merkley", "Democratic", "2009", "Incumbent", "Oregon"),
					Senator(60, "Bob Casey Jr.", "Democratic", "2007", "Incumbent", "Pennsylvania"),
					Senator(59, "Pat Toomey", "Republican", "2011", "Incumbent", "Pennsylvania"),
					Senator(71, "Jack Reed", "Democratic", "1997", "Incumbent", "Rhode Island"),
					Senator(65, "Sheldon Whitehouse", "Democratic", "2007", "Incumbent", "Rhode Island"),
					Senator(65, "Lindsey Graham", "Republican", "2003", "Incumbent", "South Carolina"),
					Senator(55, "Tim Scott", "Republican", "2013", "Incumbent", "South Carolina"),
					Senator(60, "John Thune", "Republican", "2005", "Incumbent", "South Dakota"),
					Senator(66, "Mike Rounds", "Republican", "2015", "Incumbent", "South Dakota"),
					Senator(68, "Marsha Blackburn", "Republican", "2019", "Incumbent", "Tennessee"),
					Senator(61, "Bill Hagerty", "Republican", "2021", "Incumbent", "Tennessee"),
					Senator(69, "John Cornyn", "Republican", "2002", "Incumbent", "Texas"),
					Senator(50, "Ted Cruz", "Republican", "2013", "Incumbent", "Texas"),
					Senator(49, "Mike Lee", "Republican", "2011", "Incumbent", "Utah"),
					Senator(74, "Mitt Romney", "Republican", "2019", "Incumbent", "Utah"),
					Senator(80, "Patrick Leahy", "Democratic", "1975", "Incumbent", "Vermont"),
					Senator(79, "Bernie Sanders", "Independent", "2009", "Incumbent", "Vermont"),
					Senator(66, "Mark Warner", "Democratic", "2009", "Incumbent", "Virginia"),
					Senator(63, "Tim Kaine", "Democratic", "2013", "Incumbent", "Virginia"),
					Senator(70, "Patty Murray", "Democratic", "1993", "Incumbent", "Washington"),
					Senator(62, "Maria Cantwell", "Democratic", "2001", "Incumbent", "Washington"),
					Senator(73, "Joe Manchin", "Democratic", "2010", "Incumbent", "West Virginia"),
					Senator(67, "Shelley Moore Capito", "Republican", "2015", "Incumbent", "West Virginia"),
					Senator(65, "Ron Johnson", "Republican", "2011", "Incumbent", "Wisconsin"),
					Senator(59, "Tammy Baldwin", "Democratic", "2013", "Incumbent", "Wisconsin"),
					Senator(68, "John Barrasso", "Republican", "2007", "Incumbent", "Wyoming"),
					Senator(66, "Cynthia Lummis", "Republican", "2021", "Incumbent", "Wyoming")	};
	cout << "Here are the current members of the US House of Representatives: " << endl;
	cout << "-----------------------------------------------------------------" << endl;
	for (int representative_index = 0; representative_index < REPRESENTATIVES; representative_index++) {
		cout << representatives[representative_index].GetName() << ", ";
		cout << representatives[representative_index].GetRepresentativeParty() << ", ";
		cout << representatives[representative_index].GetRepresentativeStartDate() << ", ";
		cout << representatives[representative_index].GetRepresentativeState() << ", ";
		cout << representatives[representative_index].GetRepresentativeRetiredDate() << ", ";
		cout << representatives[representative_index].GetRepresentativeAge() << endl;
	}
	cout << endl;
	cout << "Here are the current members of the US Senate: " << endl;
	cout << "-----------------------------------------------" << endl;
	for (int senator_index = 0; senator_index < SENATORS; senator_index++) {
		cout << senators[senator_index].GetName() << ", ";
		cout << senators[senator_index].GetSenatorParty() << ", ";
		cout << senators[senator_index].GetSenatorStartDate() << ", ";
		cout << senators[senator_index].GetSenatorState() << ", ";
		cout << senators[senator_index].GetSenatorRetiredDate() << ", ";
		cout << senators[senator_index].GetSenatorAge() << endl;
	}
}
